import math

# --- DISPLAY CONFIGURATION ---
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
HUD_HEIGHT = 100 
HALF_HEIGHT = SCREEN_HEIGHT // 2
GAME_TITLE = "HELL'S GRID: ALPHA EDITION"
FPS = 60

# --- RAYCASTING ENGINE CONSTANTS ---
TILE_SIZE = 64
TEXTURE_SIZE = 128
HALF_TEX = TEXTURE_SIZE // 2
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = SCREEN_WIDTH // 2
DELTA_ANGLE = FOV / NUM_RAYS
DIST = NUM_RAYS / (2 * math.tan(HALF_FOV))
SCALE = SCREEN_WIDTH // NUM_RAYS

# --- PLAYER CONTROLS & STATS ---
MOUSE_SENSITIVITY = 0.002
MOUSE_PITCH_SENSITIVITY = 2.0 
PLAYER_SPEED = 2.5 
PLAYER_SIZE = 15

MAX_HEALTH = 100
MAX_AMMO = 50 

# --- WEAPON SETTINGS ---
FIRE_RATE = 100       
RECOIL_FORCE = 12     
SHAKE_INTENSITY = 10  
GUN_SCALE = 0.6       

# --- ENEMY SETTINGS ---
ENEMY_SPEED = 1.5 
ENEMY_SIZE = 20
ENEMY_HEALTH = 100
ENEMY_DAMAGE = 0.5 

# --- UI COLORS (DARK & DINGY) ---
# Deep blood reds and dark, oxidized metals
DOOM_RED = (160, 20, 20)      # Deeper blood red
DOOM_GOLD = (180, 140, 80)    # Dull, tarnished gold
DOOM_BEVEL_LIGHT = (80, 40, 40) # Red-tinted dark light
DOOM_BEVEL_DARK = (30, 10, 10)  # Very dark red shadow
MENU_TEXT_COLOR = (100, 100, 100)
MENU_TEXT_HOVER = (200, 30, 30) 
CROSSHAIR_COLOR = (180, 40, 40) # Blood red crosshair

# --- FACE ANIMATION TIMERS ---
FACE_IDLE_MIN = 60   
FACE_IDLE_MAX = 180  
FACE_LOOK_TIME = 30